language: python
sudo: false
dist: xenial
matrix:
  include:
    - python: "3.5"
      env: TOXENV="py35-django11"
    - python: "3.5"
      env: TOXENV="py35-django20"
    - python: "3.5"
      env: TOXENV="py35-django21"
    - python: "3.5"
      env: TOXENV="py35-django22"
    - python: "3.6"
      env: TOXENV="py36-django11"
    - python: "3.6"
      env: TOXENV="py36-django20"
    - python: "3.6"
      env: TOXENV="py36-django21"
    - python: "3.6"
      env: TOXENV="py36-django22"
    - python: "3.6"
      env: TOXENV="py36-django30"
    - python: "3.7"
      env: TOXENV="py37-django11"
    - python: "3.7"
      env: TOXENV="py37-django20"
    - python: "3.7"
      env: TOXENV="py37-django21"
    - python: "3.7"
      env: TOXENV="py37-django22"
    - python: "3.7"
      env: TOXENV="py37-django30"
    - python: "3.8"
      env: TOXENV="py38-django11"
    - python: "3.8"
      env: TOXENV="py38-django20"
    - python: "3.8"
      env: TOXENV="py38-django21"
    - python: "3.8"
      env: TOXENV="py38-django22"
    - python: "3.8"
      env: TOXENV="py38-django30"
install: pip install tox
script: tox -e $TOXENV
